#!/bin/bash

DATE_HUMAN=$(date +%Y-%m-%dT%H:%m:%S)
DATE_UNIX=$(date +%s)
USER=$(whoami)
TEMPLATE="%s \t %s \t %s \t %s \n"


for i in `squeue -u $USER -t PENDING | grep gpu | awk '{print $1}'`
do
    # check and create log file
    LOG_FILENAME=$(printf "%s/log/starttime_%s.log" $HOME $i)
    if [ ! -f $LOG_FILENAME ]
    then
	printf "# jobid: %s\n" $i > $LOG_FILENAME
	printf "$TEMPLATE" "#date" "data_unix" "starttime" "starttime_unix" >> $LOG_FILENAME
    fi

    # get starttime
    STARTTIME_HUMAN=$(scontrol show job $i | grep StartTime | awk '{print $1}' | sed -e 's/StartTime=//g')
    
    if [ -f $LOG_FILENAME ]
    then
        if [ $STARTTIME_HUMAN != "Unknown" ]
        then
	    STARTTIME_UNIX=$(date -d $STARTTIME_HUMAN +%s)
	    printf "$TEMPLATE" $DATE_HUMAN $DATE_UNIX $STARTTIME_HUMAN $STARTTIME_UNIX >> $LOG_FILENAME 
        fi
    fi


done
